### ISSUE TITLE
Regression test failure - canCheckForCorrectValueBasedOnGITDocumentation

### ISSUE THREAD

**Issue by leetcooper** [eXparity/expectamundo#6]
Based on the existing example in the GIT documentation this test should pass. (I had to add SimpleTypeOldStyle due to the change to SimpleType).. It does not pass as no AssertionError is thrown.

    @Test(expected = AssertionError.class)
    public void canCheckForCorrectValueBasedOnGITDocumentation() {
      String message = "eXpectamundo lets me test this - not the same";
      SimpleTypeOldStyle expected = Expectamundo.prototype(SimpleTypeOldStyle.class);
      Expectamundo.expect(expected.getValue().get(0)).isEqualTo(message);
      List<SimpleTypeOldStyle> expectedList = Expectamundo.prototype(new TypeReference<List<SimpleTypeOldStyle>>(){});
      Expectamundo.expect(expectedList).containsExpected(expected);
      SimpleTypeOldStyle actual = new SimpleTypeOldStyle();
      Expectamundo.expectThat(Arrays.asList(actual)).matches(expectedList);
  }

**Comment by leetcooper** [comment]
I found this with these test that I would expect to be identical in function.

//WORKS
	@Test
	public void canCreateErrorResponseBuilderFromSingleError(){
		final ErrorResponse errors = prototype(ErrorResponse.class);
		final ErrorEntry expected = prototype(ErrorEntry.class);
		expect(expected.getCode()).isEqualTo(LoginFormatError.LFE01.toString());
		expect(errors.getErrors()).containsExpected(expected);
		final ErrorResponse error = new ErrorResponseBuilder().addError(LoginFormatError.LFE02).build();
		expectThat(error).matches(errors);
	}

//DOES NOT WORK	
	@Test
	public void canCreateErrorResponseBuilderFromSingleError(){
		List<ErrorEntry> errors = prototype(new TypeReference<List<ErrorEntry>>(){});
		ErrorEntry expected = prototype(ErrorEntry.class);
		expect(expected.getCode()).isEqualTo(LoginFormatError.LFE01.toString());
		expect(errors).containsExpected(expected);
		final ErrorResponse error = new ErrorResponseBuilder().addError(LoginFormatError.LFE02).build();
		expectThat(error.getErrors()).matches(errors);
	}

**Comment by stewbis** [comment]
Updated docs because the example was overcomplicated on top of being a pattern not supported by expectamundo. Updated the docs with a simpler example
